script: gem install jekyll bundler && bundle exec jekyll build
branches:
  only:
    - master
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_KEY
  bucket: theberesford.diet
  region: eu-west-1
