language: ruby
rvm:
  - 2.0
script: bundle exec jekyll build
branches:
  only:
    - master
deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_KEY
  bucket: theberesford.diet
  region: eu-west-1
  local_dir: vendor/bundle/_site
